#!/usr/bin/env bash

#################################################################################################################################

# Interface
clear
echo -e "\033[1;31mDD.Boot\033[m                         Versão 2.5 Beta"
echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"
echo -e "         Selecione o disco a ser usado "
echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"
lsblk
echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"

##################################################################################################################################
echo -e "Adicione apenas o identificador de disco"
echo -e "identificado como sd?, sem o uso de numeros\n \c"


# Funções

read disc

[[ ! -z $disc ]]

echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"
echo -e "Copie e cole a iso a ser usada"
echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"
echo -e " \c"
read iso

[[ ! -z $iso ]] && sudo dd if=$iso of=/dev/$disc status=progress

echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"
echo -e "Tudo pronto, seu pendrive ja pode ser usado."
echo -e "\033[1;36m▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\033[m"

